version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: jest-image-snapshot
    versions:
    - 4.3.0
    - 4.4.0
  - dependency-name: "@babel/plugin-transform-typescript"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: lodash
    versions:
    - 4.17.20
